### ISSUE TITLE
Move `SqlTypes` to core

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures-cmd#14]
1. Move enum `SqlTypes` to core https://github.com/vkorobkov/jfixtures.

2. Add a method into `com.github.vkorobkov.jfixtures.JFixtures`:
```java
public static JFixturesResult byDialect(SqlTypes type)
```
3. Make `SqlTypes` enum responsible for instantiating SQL dialects

4. Release a new minor version of core

5. Simplify jfixtures-cmd using these changes

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/16

**Comment by rodionovsasha** [comment]
issue completed under https://github.com/vkorobkov/jfixtures-cmd/pull/15.
so close it!
