### ISSUE TITLE
Add minimal verbosity

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures-cmd#16]
Add minimal verbosity to show how progress goes, where the fixtures are, succeed of failed, where the result was stored into, the time it took.

**Comment by rodionovsasha** [comment]
PR: https://github.com/vkorobkov/jfixtures-cmd/pull/19

**Comment by rodionovsasha** [comment]
https://github.com/vkorobkov/jfixtures-cmd/pull/19 merged
