### ISSUE TITLE
Create a fully integration test

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures-cmd#8]
This test should be executed after the `jar` artifact is built in the `target` folder:
1. go to `target`
2. execute `java -jar jfixtures-cmd-X.XX.jar --help` (where X.XX is floating version)
3. Wait until the execution is done
4. Check OS returned code `0`(no errors) otherwise test should be failed

It could be implemented like a groovy script which we can run from Maven, the main goal is just to check that the assembled JAR is launching. Though, if it is possible to run such integration test with spock+maven, separately from unit tests and strictly after the `JAR` artifact is built in the `target` folder - would be even better.

**Comment by rodionovsasha** [comment]
PR: https://github.com/vkorobkov/jfixtures-cmd/pull/17
